{
  "name": "seerportal",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "antd": "^3.20.3",
    "axios": "^0.21.1",
    "classnames": "^2.2.6",
    "crypto-browserify": "^3.12.0",
    "csvjson-csv2json": "^5.0.6",
    "detect-browser": "^5.1.1",
    "downloadjs": "^1.4.7",
    "echarts": "^5.0.2",
    "echarts-for-react": "^3.0.1",
    "enzyme": "^3.10.0",
    "enzyme-adapter-react-16": "^1.14.0",
    "highcharts": "^9.1.2",
    "highcharts-react-official": "^3.0.0",
    "history": "^4.10.1",
    "html2pdf.js": "^0.9.0",
    "is-valid-domain": "0.0.11",
    "joi": "^17.1.1",
    "md5": "^2.2.1",
    "moment": "^2.24.0",
    "node-sass": "^4.13.1",
    "prop-types": "^15.7.2",
    "react": "^16.8.6",
    "react-accessible-accordion": "^3.0.0",
    "react-app-polyfill": "^1.0.6",
    "react-beautiful-dnd": "^13.0.0",
    "react-dom": "^16.8.6",
    "react-geocode": "^0.2.1",
    "react-google-maps": "^9.4.5",
    "react-icons": "^4.2.0",
    "react-idle-timer": "^4.2.12",
    "react-iframe": "^1.8.0",
    "react-json-to-csv": "^1.0.4",
    "react-json-view": "^1.19.1",
    "react-lazy-load-image-component": "^1.4.1",
    "react-quill": "^1.3.5",
    "react-redux": "^7.1.0",
    "react-router-dom": "^5.0.1",
    "react-scripts": "^3.3.0",
    "react-show-more-text": "^1.4.2",
    "react-tagcloud": "^2.1.1",
    "react-test-renderer": "^16.8.6",
    "recompose": "^0.30.0",
    "redux": "^4.0.4",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0",
    "reqwest": "^2.0.5",
    "string-template": "^1.0.0",
    "tslib": "^2.3.0",
    "xlsx-parse-json": "^3.1.0",
    "yarn-install": "^1.0.0"
  },
  "scripts": {
    "start": "webpack serve --progress",
    "prod-build": "webpack build --progress --no-devtool --mode production",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version",
      "ie 11",
      "ie 9"
    ]
  },
  "devDependencies": {
    "babel-loader": "^8.2.2",
    "babel-preset-react": "^6.24.1",
    "clean-webpack-plugin": "^4.0.0-alpha.0",
    "compression-webpack-plugin": "^8.0.1",
    "css-loader": "^6.2.0",
    "css-minimizer-webpack-plugin": "^3.0.2",
    "file-loader": "^6.2.0",
    "html-webpack-plugin": "^5.3.2",
    "mini-css-extract-plugin": "^2.2.0",
    "node-polyfill-webpack-plugin": "^1.1.4",
    "raw-loader": "^4.0.2",
    "sass-loader": "^12.1.0",
    "webpack": "^5.50.0",
    "webpack-cli": "^4.7.2",
    "webpack-dev-server": "^3.11.2"
  }
}
